excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://hackroll.github.io
title: Hack 'n Roll
tagline: Knowledge is Power
description: Tentando dominar o mundo com o poder do Rock e do JavaScript
paginate: 3
